diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=main
core.editor="C:\Users\Graemedunlop\AppData\Local\Programs\Microsoft VS Code\bin\code" --wait
user.name=g-dunlop
user.email=graemedunlop1983@gmail.com
safe.directory=C:/Users/Graemedunlop/Documents/Coding/ReactNative/FirebaseAuth
safe.directory=C:/Users/Graemedunlop/Documents/Coding/ToDoApp
safe.directory=C:/Users/Graemedunlop/Documents/Coding/instaClone
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
core.hookspath=.husky
remote.origin.url=https://github.com/Scottish-Tech-Army/Volunteer-app.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.main.remote=origin
branch.main.merge=refs/heads/main
branch.Feature/SVA-201-Add-STA-Contact-details.remote=origin
branch.Feature/SVA-201-Add-STA-Contact-details.merge=refs/heads/Feature/SVA-201-Add-STA-Contact-details
branch.Feature/SVA-13-Welcome-info-Display-welcome-page.remote=origin
branch.Feature/SVA-13-Welcome-info-Display-welcome-page.merge=refs/heads/Feature/SVA-13-Welcome-info-Display-welcome-page
branch.feature/SVA-82-see-event-detail.remote=origin
branch.feature/SVA-82-see-event-detail.merge=refs/heads/feature/SVA-82-see-event-detail
branch.SVA-86-past-events.remote=origin
branch.SVA-86-past-events.merge=refs/heads/SVA-86-past-events
branch.SVA-219-welcome-info-only-show-on-first-use-of-the-app.remote=origin
branch.SVA-219-welcome-info-only-show-on-first-use-of-the-app.merge=refs/heads/SVA-219-welcome-info-only-show-on-first-use-of-the-app
